### ISSUE TITLE
サイドバーのqiitaの投稿から対象ファイルをクリックしても表示されない

### ISSUE THREAD

**Issue by mokusen** [neet/vscode-qiita#12]
表題の件、
クリックすると、「ファイルの表示に失敗しました。指定された投稿は存在しない可能性があります。」と通知に表示されます。
対象のqiitaに投稿されている記事は存在し、「ブラウザで表示」を選択すると、ブラウザでは表示されます。

### バージョン情報
| name   | version |
| :----- | :------ |
| OS     |    Windows10(Home)     |
| VSCode |    1.28.2     |

---

- [x] 同様のissue及びpull requestが無いか調べました。
- [x] この問題はmasterブランチではなくダウンロード可能なリリースで発生しています。

**Comment by neet** [comment]
こんにちは、バグのご報告ありがとうございます！

私の環境でも同様のバグが再現でき、当該のものと思われるコードを修正し、先程 [0.1.5](https://github.com/neet/vscode-qiita/releases/tag/0.1.5) をリリースいたしましたので、お手数ですが最新版に更新していただき、バグが修正されたかご確認いただいてもよろしいでしょうか。（環境によっては更新が利用可能になるまで数時間ラグがある場合がございます）

よろしくお願いします。
#### 参考
- #14

**Comment by mokusen** [comment]
こんにちは、短時間での修正お疲れ様です！

0.1.5にアップグレードし、修正されたことが確認できました。
有難う御座いました！

**Comment by neet** [comment]
ご返信ありがとうございます、解決したようで何よりです！
また問題が発生した場合はご報告いただけると幸いです。
